#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>
#include <ctype.h>
#include <Windows.h>

bool isprime(long long int n)
//will tell if a number is prime or not
{
    if (n <= 1)
        return false;
    for (long long int i = 2; i * i <= n; i++)
    {
        if (n % i == 0)
            return false;
    }
    return true;
}

long long int genrandomprime(long long int ll, long long int ul)
//will generate a random prime number in the range ll to ul
{
    long long int range = ul - ll + 1;
    long long int randno = rand() % range + ll;
    while (!isprime(randno))
        randno = rand() % range + ll;
    return randno;
}

long long int secure(long long int g, int x, long long int n)
//will compute g^x mod n to generate a secure key
{
    int i;
    long long int l = 1;
    for (i = 0; i < x; i++)
        l = (l % n) * g;
    return l % n;
}

void encryptFile(const char *filename, long long key) {
    int div_count = 0;
    FILE *inputFile, *outputFile;
    char ch;
    long long key_copy=key;
    inputFile = fopen(filename, "r");
    if (inputFile == NULL) {
        printf("Error opening the file.\n");
        return;
    }
    outputFile = fopen("encrypted.txt", "w");
    if (outputFile == NULL) {
        printf("Error creating the encrypted file.\n");
        fclose(inputFile);
        return;
    }
    while ((ch = fgetc(inputFile)) != EOF) {
        if (!isspace(ch)) {
            ch += (key_copy % 10); // Encrypting the character

            // Wrap around if necessary
            if (ch > 127)
                ch = 32 + (ch - 127);
            else if (ch < 32)
                ch = 127 - (32 - ch);

            key_copy /= 10; // Move to the next digit in the key
            div_count++;
            if(div_count>7)
            {
                key_copy=key;
                div_count=0;
            }
        }
        fputc(ch, outputFile);
        if (isspace(ch)) {
            // Restore the key
            key_copy = key;
        }
    }
    fclose(inputFile);
    fclose(outputFile);
    printf("File encrypted successfully!\n");
}

void decryptFile(const char *filename, long long key) {
    FILE *inputFile, *outputFile;
    char ch;
    int div_count=0;
    long long key_copy=key;

    inputFile = fopen(filename, "r");
    if (inputFile == NULL) {
        printf("Error opening the file.\n");
        return;
    }
    outputFile = fopen("decrypted.txt", "w");
    if (outputFile == NULL) {
        printf("Error creating the decrypted file.\n");
        fclose(inputFile);
        return;
    }
    while ((ch = fgetc(inputFile)) != EOF) {
        if (!isspace(ch)) {
            ch -= (key_copy % 10); // Decrypting the character
            // Wrap around if necessary
            if (ch < 32)
                ch = 127 - (32 - ch);
            else if (ch > 127)
                ch = 32 + (ch - 127);

            key_copy /= 10; // Move to the next digit in the key
            div_count++;
            if(div_count>7)
            {
                key_copy=key;
                div_count=0;
            }
        }
        fputc(ch, outputFile);
        if (isspace(ch)) {
            // Restore the key
            key_copy = key;
            // key += ch - ' ';
        }
    }

    fclose(inputFile);
    fclose(outputFile);
    printf("File decrypted successfully!\n");
}
void clearScreen()
{
    system("cls");
}

void changeTextColor(WORD color)
{
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
}

void printHeading(const char *text)
{
    changeTextColor(FOREGROUND_BLUE | FOREGROUND_INTENSITY);
    printf("\n%s\n", text);
    changeTextColor(FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE);
}

void printMessage(const char *text)
{
    changeTextColor(FOREGROUND_GREEN);
    printf("%s", text);
    changeTextColor(FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE);
}

int main()

{
    int x, y;
    long long int A, B, K1, K2, g, n, ll = 1000000000, ul = 9999999999; // lower and upper limits for prime no. generation
    srand(time(NULL));
    g = genrandomprime(ll, ul);
    n = genrandomprime(ll, ul);
    printHeading("Secure Communication Program");
    printf("\n");
    printf("Randomly generated big prime numbers are %lld and %lld\n", g, n);
    // Sleep(1000);
    printf("Enter the number private to person 1 : ");
    scanf("%d", &x);
    printf("Enter the number private to person 2 : "); // Only Alicee knows x and only Bob knows y
    scanf("%d", &y);
    A = secure(g, x, n);
    B = secure(g, y, n); // Both A and B are exchanged between Alice and Bob via a public domain .
    Sleep(500);
    printf("\nPublic key generated by person 1 : %lld\n", A);
    printf("Public key generated by person 2 : %lld\n", B);
    Sleep(500);
    printf("\nSecure keys generated by person 1 and person 2 are : ");
    K1 = secure(B, x, n);
    K2 = secure(A, y, n); // line 21,24 computed privately in Alice's system and line 22,25 computed privately in Bob's system
    if (K1 == K2){
        printf("%lld and %lld\n", K1, K2);
        printf("K1 = K2 = %lld\nHence a symmetric key is generated .\n", K1,K2);
    }
    else
        printf("The Keys generated are not symmetric .\nK1 = %lld K2 = %lld\n", K1, K2);

        printf("\n\nPress Enter to see the secure communication taking place\n");
        
        fflush(stdin);
        getchar();
        clearScreen();
        
        printHeading("Secure Communication in Progress...");
        Sleep(2000);
        printf("\nA started encrypting the file with his symmetric copy of key\n");
        Sleep(1000);
        printMessage("Encrypting");
        for(int i=0;i<5;i++)
        {
            Sleep(500);
            printMessage(".");
        }
        printf(".\n");
        encryptFile("message.txt",K1);
        Sleep(2000);
        printf("\nEncrypted file being sent to B\n");
         printMessage("Sending");
        for(int i=0;i<5;i++)
        {
            Sleep(500);
            printMessage(".");
        }
        printf(".\n");
        Sleep(2000);
        printf("File sent successfully\n");
        Sleep(2000);
        printf("\nB received the file\n");
        Sleep(2000);
        printf("\nB started decrypting the file with his symmetric copy of key\n");
        Sleep(1000);
         printMessage("Decrypting");
        for(int i=0;i<5;i++)
        {
            Sleep(500);
             printMessage(".");
        }
        printf(".\n");
        decryptFile("encrypted.txt",K2);
    
        Sleep(2000);
       printHeading("Secure Communication Completed Successfully");
        Sleep(2000);
         printMessage("Exiting...");




    return 0;
}
